name: Hexo Site Deployment

on:
  push:
    branches:
      - butterfly
    paths-ignore:
      - .github/**
      - .yarn/**
      - LICENSE.txt
      - README.md
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  deploy:
    name: Hexo Site Deployment
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          # We need full history so Hexo can show correct creation time for each post
          fetch-depth: 0
          # We use Git Submodules to include themes, so we need this
          submodules: true
      - uses: threeal/setup-yarn-action@v2
        name: Setup Node.js environment
        with:
          version: latest
          cache: true
      # The above step does not cache the node_modules directory
      # So the following step is necessary
      - name: Configure Yarn
        run: yarn config set nodeLinker node-modules
      - name: Install required dependencies
        run: yarn install --immutable
      - name: Execute compilation and build
        run: yarn run build
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy site
        id: deploy
        uses: actions/deploy-pages@v4
